### ISSUE TITLE
Propose minor change for performance

### ISSUE THREAD

**Issue by wishfoundry** [Skinney/elm-array-exploration#7]
[Patch Here](https://github.com/Skinney/elm-array-exploration/compare/master...wishfoundry:patch-1)

**Comment by Skinney** [comment]
Have you tested this in all browsers? I seem to remember doing this, but it made Safari/Firefox slower.

**Comment by wishfoundry** [comment]
It's a diminishing return depending on the length of the array, above 1000 Array#slice() tends to be favorable. since we're only deal with 32 length arrays, this always better(at least in recent FF, safari, chrome).

I thought it had to do with array capacity allocation when length is not provided, which would explain the diminishing return. But I can't seem to remember or find that data anymore. 
It's yielded measurable improvements for me on my project.

**Comment by Skinney** [comment]
Cool!

Here's the thing. I've already sent a PR to the elm-lang/core repo, and it has been merged. Could you send your own PR to that repo on the dev branch with these changes?

To increase the chances of Evan merging this, you need to include benchmark information for all three browsers in the description of the PR.
