### ISSUE TITLE
Runtime error with Array.slice

### ISSUE THREAD

**Issue by mpizenberg** [Skinney/elm-array-exploration#8]
Hi, I've been trying your implementation of Array and got a runtime error while using `Array.slice`. It boils down to:
```elm
> Array.repeat (33*32) 1 |> Array.slice 0 1
TypeError: Cannot read property 'ctor' of undefined
```

**Comment by Skinney** [comment]
Thanks for this. This is fixed in version 2.0.4. Available from elm-package now.
