### ISSUE TITLE
better import

### ISSUE THREAD

**Issue by pdavidow** [Skinney/elm-array-exploration#9]
http://package.elm-lang.org/packages/Skinney/elm-array-exploration/2.0.4/ suggests `import Array.Hamt as Array`.  But `import Array.Hamt as Array exposing (..)` appears to better.

**Comment by Skinney** [comment]
Define "better".

Besides, it doesn't suggest one way of import over another. It tells you to change the import you currently use, for this package to be used instead, without any other code change.
